# Generated by Django 2.2.8 on 2023-05-25 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaConsulta', models.CharField(max_length=200)),
                ('medicoVeterinario', models.CharField(max_length=200)),
                ('motivoConsulta', models.CharField(max_length=200)),
                ('sintomatologia', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=200)),
                ('procedimiento', models.CharField(max_length=200)),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=200)),
                ('idOrden', models.CharField(max_length=200)),
                ('historialVacunacion', models.CharField(max_length=200)),
                ('alergiasMedicamentos', models.CharField(max_length=200)),
                ('detalleProcedimiento', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Historia_clinica',
            },
        ),
        migrations.CreateModel(
            name='OrdenMascotas',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('idMascota', models.CharField(max_length=200)),
                ('cedulaDueno', models.CharField(max_length=200)),
                ('cedulaVeterinario', models.CharField(max_length=200)),
                ('nombreMedicamento', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Orden',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=200)),
                ('Contraseña', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=3)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinariaApp.Rol')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('cedula_dueño', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=200)),
                ('especie', models.CharField(max_length=200)),
                ('raza', models.CharField(max_length=200)),
                ('caracteristicas', models.CharField(max_length=200)),
                ('peso', models.CharField(max_length=3)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.Usuario')),
            ],
            options={
                'db_table': 'Mascota',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('idMascota', models.CharField(max_length=200)),
                ('cedulaDueño', models.CharField(max_length=200)),
                ('idOrden', models.CharField(max_length=200)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.Usuario')),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
    ]
